version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://db:3306/mydiary
      DB_USER: myuser
      DB_PASSWORD: mypassword
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-database
    environment:
      MYSQL_DATABASE: mydiary
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
